AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SSM Data Fetcher - Lambda Deployment

Parameters:
  # Deployment configuration
  S3BucketName:
    Type: String
    Description: S3 bucket for storing output data and cache (must be globally unique)
    Default: aws-data-fetcher-output

  ScheduleExpression:
    Type: String
    Description: Schedule for automatic updates (EventBridge cron/rate expression)
    Default: cron(0 2 * * ? *)  # Daily at 2 AM UTC

  BatchSize:
    Type: Number
    Description: Parallel region processing batch size (10=conservative, 12=balanced, 15=aggressive)
    Default: 10
    MinValue: 5
    MaxValue: 20

  PaginationDelay:
    Type: Number
    Description: Delay between SSM pagination requests in milliseconds
    Default: 40
    MinValue: 20
    MaxValue: 100

  NotificationEmail:
    Type: String
    Description: Email address for success and error notifications
    Default: ''

  DistributionBucketName:
    Type: String
    Default: www.aws-services.synepho.com
    Description: S3 bucket for CloudFront distribution (leave empty to disable distribution)

  DistributionKeyPrefix:
    Type: String
    Default: data
    Description: Key prefix in distribution bucket for data files

  # Tagging parameters
  Environment:
    Type: String
    Default: prod
    Description: Environment identifier (prod, staging, dev)
    AllowedValues: [prod, staging, dev]

  ProjectName:
    Type: String
    Default: aws-services
    Description: Project name identifier

  ServiceName:
    Type: String
    Default: aws-infrastructure-data-fetcher
    Description: Service name identifier

  GithubRepository:
    Type: String
    Default: github.com/jxman/aws-infrastructure-fetcher
    Description: GitHub repository path

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, '']]
  HasDistributionBucket: !Not [!Equals [!Ref DistributionBucketName, '']]

# Global tags applied to all compatible resources (Lambda functions)
Globals:
  Function:
    Tags:
      Environment: !Ref Environment
      ManagedBy: sam
      Owner: John Xanthopoulos
      Project: !Ref ProjectName
      Service: !Ref ServiceName
      GithubRepo: !Ref GithubRepository

Resources:
  # S3 Bucket for outputs and cache
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # Delete old historical snapshots after 30 days
          - Id: DeleteOldHistoryFiles
            Prefix: aws-data/history/
            Status: Enabled
            ExpirationInDays: 30
          # Keep current data and cache indefinitely
          - Id: KeepCurrentData
            Prefix: aws-data/
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: aws-data-fetcher-output-bucket
        - Key: SubService
          Value: output-bucket

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: aws-data-fetcher-notifications
      DisplayName: AWS Data Fetcher Notifications
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: aws-data-fetcher-notifications
        - Key: SubService
          Value: notification-topic

  # SNS Email Subscription
  NotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasNotificationEmail
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  # Lambda Function
  DataFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-data-fetcher
      CodeUri: ./
      Handler: src/lambda/infra-data-handler.handler
      Runtime: nodejs20.x
      Description: Fetches AWS infrastructure data from SSM (complete with service mapping)
      Timeout: 180  # 3 minutes (77s runtime + buffer)
      MemorySize: 512
      Environment:
        Variables:
          # Storage configuration
          STORAGE_TYPE: s3
          S3_BUCKET_NAME: !Ref OutputBucket
          S3_PREFIX: aws-data

          # Performance tuning (from config.js)
          BATCH_SIZE: !Ref BatchSize
          PAGINATION_DELAY: !Ref PaginationDelay
          CACHE_TTL: 86400000  # 24 hours in milliseconds

          # Notifications
          SNS_TOPIC_ARN: !Ref NotificationTopic

          # Distribution configuration
          DISTRIBUTION_BUCKET: !Ref DistributionBucketName
          DISTRIBUTION_PREFIX: !Ref DistributionKeyPrefix

          # Logging
          LOG_LEVEL: info
          NODE_ENV: production
      Policies:
        # SSM read-only access
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}::parameter/aws/service/global-infrastructure/*'
        # S3 access for data and cache
        - S3CrudPolicy:
            BucketName: !Ref OutputBucket
        # SNS publish for notifications
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Ref NotificationTopic
        # S3 write access for distribution bucket (only if configured)
        - !If
          - HasDistributionBucket
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub 'arn:aws:s3:::${DistributionBucketName}/${DistributionKeyPrefix}/*'
          - !Ref AWS::NoValue
      Events:
        # Daily EventBridge schedule
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Daily AWS data fetch
            Enabled: true
            Input: |
              {
                "includeServiceMapping": true,
                "forceRefresh": false
              }
      Tags:
        Name: aws-data-fetcher-lambda
        SubService: data-fetcher-lambda
        # Globals tags automatically merged: Environment, ManagedBy, Owner, Project, Service, GithubRepo

  # CloudWatch Log Group (explicit creation for retention control)
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${DataFetcherFunction}'
      RetentionInDays: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: data-fetcher-log-group
        - Key: SubService
          Value: data-fetcher-logs

  # CloudWatch Alarm - Error detection
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-data-fetcher-errors
      AlarmDescription: Alert when Lambda function encounters errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DataFetcherFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopic
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: data-fetcher-error-alarm
        - Key: SubService
          Value: data-fetcher-error-monitoring

  # CloudWatch Alarm - Duration monitoring
  DurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-data-fetcher-duration
      AlarmDescription: Alert when Lambda execution exceeds expected duration
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 120000  # 120 seconds (2 minutes)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DataFetcherFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopic
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: data-fetcher-duration-alarm
        - Key: SubService
          Value: data-fetcher-duration-monitoring

  # NEW: Lambda Function for AWS What's New RSS Feed
  WhatsNewFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-whats-new-fetcher
      CodeUri: ./
      Handler: src/lambda/whats-new-handler.handler
      Runtime: nodejs20.x
      Description: Fetches AWS What's New announcements from last 14 days (max 100 items)
      Timeout: 30  # 30 seconds (RSS fetch is fast)
      MemorySize: 256  # Lightweight operation
      Environment:
        Variables:
          # RSS Feed configuration
          RSS_FEED_URL: https://aws.amazon.com/about-aws/whats-new/recent/feed/
          DAYS_TO_INCLUDE: 14
          MAX_ITEMS: 100

          # Source bucket configuration (for consistency)
          S3_BUCKET_NAME: !Ref OutputBucket
          S3_PREFIX: aws-data

          # Distribution configuration
          DISTRIBUTION_BUCKET: !Ref DistributionBucketName
          DISTRIBUTION_PREFIX: !Ref DistributionKeyPrefix

          # Notifications
          SNS_TOPIC_ARN: !Ref NotificationTopic

          # Logging
          LOG_LEVEL: info
          NODE_ENV: production
      Policies:
        # S3 write access for source bucket (for consistency)
        - S3CrudPolicy:
            BucketName: !Ref OutputBucket
        # S3 write access for distribution bucket (only if configured)
        - !If
          - HasDistributionBucket
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub 'arn:aws:s3:::${DistributionBucketName}/${DistributionKeyPrefix}/*'
          - !Ref AWS::NoValue
        # SNS publish for notifications
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Ref NotificationTopic
      Events:
        # Four times daily EventBridge schedule (every 6 hours)
        Schedule2AM:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 * * ? *)
            Description: AWS What's New feed fetch - 2 AM UTC
            Enabled: true
        Schedule8AM:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
            Description: AWS What's New feed fetch - 8 AM UTC
            Enabled: true
        Schedule2PM:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)
            Description: AWS What's New feed fetch - 2 PM UTC
            Enabled: true
        Schedule8PM:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Description: AWS What's New feed fetch - 8 PM UTC
            Enabled: true
      Tags:
        Name: aws-whats-new-fetcher-lambda
        SubService: whats-new-fetcher-lambda
        # Globals tags automatically merged: Environment, ManagedBy, Owner, Project, Service, GithubRepo

  # CloudWatch Log Group for What's New fetcher
  WhatsNewFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${WhatsNewFetcherFunction}'
      RetentionInDays: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: whats-new-fetcher-log-group
        - Key: SubService
          Value: whats-new-logs

  # CloudWatch Alarm - What's New error detection
  WhatsNewErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-whats-new-fetcher-errors
      AlarmDescription: Alert when What's New fetcher encounters errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref WhatsNewFetcherFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopic
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: whats-new-error-alarm
        - Key: SubService
          Value: whats-new-error-monitoring

  # CloudWatch Alarm - What's New duration monitoring
  WhatsNewDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-whats-new-fetcher-duration
      AlarmDescription: Alert when What's New fetcher execution exceeds expected duration
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10000  # 10 seconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref WhatsNewFetcherFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopic
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: sam
        - Key: Owner
          Value: John Xanthopoulos
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: GithubRepo
          Value: !Ref GithubRepository
        - Key: Name
          Value: whats-new-duration-alarm
        - Key: SubService
          Value: whats-new-duration-monitoring

Outputs:
  OutputBucketName:
    Description: S3 bucket for output data and cache
    Value: !Ref OutputBucket
    Export:
      Name: !Sub '${AWS::StackName}-OutputBucket'

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt DataFetcherFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  LambdaFunctionName:
    Description: Lambda function name (for manual invocation)
    Value: !Ref DataFetcherFunction

  ScheduleExpression:
    Description: EventBridge schedule expression
    Value: !Ref ScheduleExpression

  S3DataUrl:
    Description: S3 console URL for data files
    Value: !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${OutputBucket}?prefix=aws-data/'

  NotificationTopicArn:
    Description: SNS topic ARN for notifications
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  WhatsNewFunctionArn:
    Description: What's New fetcher Lambda function ARN
    Value: !GetAtt WhatsNewFetcherFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WhatsNewFunctionArn'

  WhatsNewFunctionName:
    Description: What's New fetcher function name (for manual invocation)
    Value: !Ref WhatsNewFetcherFunction

  WhatsNewDataUrl:
    Description: Public URL for AWS What's New data
    Value: !Sub 'https://aws-services.synepho.com/${DistributionKeyPrefix}/aws-whats-new.json'
